/** Explicit Cordis-free source owners in the native production graph. */

/** Package sources validated from their selected compiler faces by verify-native-dependencies. */
export const nativePackageDirectories: ReadonlySet<string> = new Set([
  'rsh/Programs/TUI/native-tui',
  'rsh/Programs/TUI/terminal-ui',
  'rsh/Core/identity/anonymous-user-id',
  'rsh/Modules/Official/shell/shell-process-local',
  'rsh/Modules/Official/shell/shell-sandbox-core',
  'rsh/Core/subprocess/win32-process',
  'rsh/Core/util/http-proxy',
  'rsh/Core/util/atomic-write',
  'rsh/Core/runtime-diagnostics/native-runtime',
  'rsh/Core/util/brand',
  'rsh/Core/util/crypto',
  'rsh/Core/util/errors',
  'rsh/Core/util/home-paths',
  'rsh/Core/util/json-rpc-line',
  'rsh/Core/util/native-command',
  'rsh/Core/util/output-retention',
  'rsh/Core/util/timeout',
  'rsh/Core/util/values',
  'rsh/Engine/session/session-format',
  'rsh/Engine/session/session-format-catalog',
  'rsh/Engine/session/session-format-v0-to-v1',
  'rsh/Engine/session/session-format-v1-to-v2',
  'rsh/Engine/session/session-format-v2-to-v3',
  'rsh/Engine/context/native-time-context',
  'rsh/Engine/workspace/workspace-definition',
  'rsh/Engine/core/native-agent',
  'rsh/Engine/core/native-session-execution',
  'rsh/Engine/core/native-code-runtime',
  'rsh/Modules/Official/code-runtime/tool-code-runtime',
  'rsh/Modules/Official/code-runtime/code-runtime-process-sandbox',
  'rsh/Engine/core/native-headless',
  'rsh/Engine/core/native-jobs',
  'rsh/Engine/core/native-model-execution',
  'rsh/Engine/llm/native-model-selection',
  'rsh/Engine/core/native-prompt',
  'rsh/Engine/core/native-tools',
  'rsh/Engine/jobs/native-tool-jobs',
  'rsh/Modules/Official/interaction/native-approval',
  'rsh/Modules/Official/interaction/user-question-broker',
  'rsh/Modules/Official/sandbox/native-sandbox-policy',
  'rsh/Modules/Official/sandbox/sandbox-windows-acl',
  'rsh/Programs/Web/api/native-web-session-controller',
  'rsh/Programs/Web/client/native-session',
  'rsh/Programs/Web/client/native-application',
  'rsh/Programs/Web/host/native-web-host',
  'rsh/Programs/ACP/packages/native-acp',
  'rsh/Programs/SDK/packages/native-server',
  'rsh/Programs/Web/host/native-web-assets',
  'rsh/Programs/Web/client/store',
  'rsh/Programs/Web/client/ui-slots',
])

/** Explicit compiler faces for pure packages with a Host-only implementation. */
export const nativePackageTargets: ReadonlyMap<string, readonly ('host' | 'client')[]> = new Map([
  ['rsh/Programs/TUI/native-tui', ['host']],
  ['rsh/Programs/TUI/terminal-ui', ['host']],
  ['rsh/Core/identity/anonymous-user-id', ['host']],
  ['rsh/Modules/Official/shell/shell-process-local', ['host']],
  ['rsh/Modules/Official/shell/shell-sandbox-core', ['host']],
  ['rsh/Engine/core/native-tools', ['host']],
  ['rsh/Engine/core/native-model-execution', ['host']],
  ['rsh/Engine/llm/native-model-selection', ['host']],
  ['rsh/Modules/Official/interaction/user-question-broker', ['host']],
  ['rsh/Engine/core/native-session-execution', ['host']],
  ['rsh/Modules/Official/sandbox/sandbox-windows-acl', ['host']],
  ['rsh/Engine/core/native-code-runtime', ['host']],
  ['rsh/Modules/Official/code-runtime/tool-code-runtime', ['host']],
  ['rsh/Modules/Official/code-runtime/code-runtime-process-sandbox', ['host']],
  ['rsh/Programs/Web/api/native-web-session-controller', ['host']],
  ['rsh/Programs/Web/client/native-session', ['client']],
  ['rsh/Programs/Web/client/native-application', ['client']],
  ['rsh/Programs/Web/host/native-web-host', ['host']],
  ['rsh/Programs/ACP/packages/native-acp', ['host']],
  ['rsh/Programs/SDK/packages/native-server', ['host']],
  ['rsh/Programs/Web/host/native-web-assets', ['host']],
])

/** Mixed legacy packages whose Cordis entry and native installer share a package. */
export const mixedNativeEntryDirectories: ReadonlyMap<string, string> = new Map([
  ['rsh/Modules/Official/todo/tool-todo', 'Native and Cordis todo consumers share list normalization and durable Session events'],
  ['rsh/Modules/Official/fs/tool-fs-search', 'Cordis and native search Consumers share ripgrep execution, parsing and result retention'],
  ['rsh/Modules/Official/spill/spill-local', 'Cordis and native spill Providers share private writes and startup cleanup'],
  ['rsh/Engine/context/agent-instructions', 'Native and Cordis instruction Providers share discovery, rendering and durable reconciliation'],
  ['rsh/Modules/Official/interaction/user-questions', 'Native and Cordis human questions share protocol values and errors'],
  ['rsh/Modules/Official/interaction/tool-ask-user', 'Native and Cordis Consumers use the selected human question service'],
  ['rsh/Modules/Official/mcp/mcp-client', 'Cordis and native MCP Consumers share connection supervision and protocol tool projection'],
  ['rsh/Modules/Official/sandbox/sandbox-local', 'Cordis and native Providers share local confinement and grant ownership'],
  ['rsh/Modules/Official/shell/shell-env', 'Cordis and native installers share managed command environment facts'],
  ['rsh/Modules/Official/shell/bash-local', 'Cordis and native installers share managed process operations'],
  ['rsh/Modules/Official/shell/bash-sandbox', 'Cordis and native installers share confined process operations'],
  ['rsh/Modules/Official/shell/pwsh-local', 'Cordis and native installers share managed process operations'],
  ['rsh/Modules/Official/shell/pwsh-sandbox', 'Cordis and native installers share confined process operations'],
  ['rsh/Modules/Official/shell/tool-bash', 'Cordis and native Consumers share Bash tool presentation'],
  ['rsh/Modules/Official/shell/tool-pwsh', 'Cordis and native Consumers share PowerShell tool presentation'],
  ['rsh/Modules/Official/terminal/terminal', 'Cordis and native Definitions share Agent-owned PTY lifecycle'],
  ['rsh/Modules/Official/terminal/terminal-bash', 'Cordis and native Providers share the subprocess terminal primitive'],
  ['rsh/Modules/Official/terminal/tool-terminal', 'Cordis and native Consumers share terminal lifecycle tools'],
  ['rsh/Modules/Official/fs/tool-fs', 'Cordis and native value tools share filesystem validation, guards and presentation'],
  ['rsh/Modules/Official/attachment/attachment-local', 'Cordis and native attachment Providers share immutable objects and transform ownership'],
  ['rsh/Engine/llm/llm-pi-ai', 'Cordis and native pi-ai Providers share real adapter, catalog and auth operations'],
  ['rsh/Engine/llm/llm-deepseek', 'Cordis and native official Providers share real HTTP/SSE adapter and static configuration'],
  ['rsh/Core/subprocess/subprocess-local', 'Cordis and native Providers share managed process and terminal ownership'],
  ['rsh/Programs/Web/client/ui-renderer', 'Cordis and native Client entries share slot rendering'],
  ['rsh/Programs/Web/client/connection', 'Cordis and native Client entries share authenticated transport'],
  ['rsh/Core/storage/storage', 'Cordis and native storage hubs share the backend registry'],
  ['rsh/Core/storage/storage-json', 'Cordis and native JSON Providers share atomic storage operations'],
  ['rsh/Core/storage/storage-domain', 'Cordis and native domain Providers share schemas and durability'],
  ['rsh/Engine/preset/agent-presets', 'Native standing composition leases and compatibility presets share durable selection facts'],
  ['rsh/Modules/Official/workspace/workspace', 'Native and Cordis Workspace Providers share the durable v2 registry'],
  ['rsh/Modules/Official/credentials/credentials-local', 'Cordis service and native credential installer share the file backend'],
  ['rsh/Modules/Official/settings/settings-file', 'Cordis and native settings Providers share the document format and atomic file owner'],
  ['rsh/Engine/session/session-persistence-jsonl', 'Cordis service and native storage entry share a package'],
  ['rsh/Modules/Official/fs/fs-local', 'Cordis filesystem Provider and native backend share a package'],
  ['rsh/Modules/Official/fs/fs-observation-policy', 'Cordis event policy and native entry share a package'],
])

/** Mixed library exports that have native values or types but no installer manifest. */
export const mixedNativeLibraryDirectories: ReadonlyMap<string, readonly ('host' | 'client')[]> = new Map([
  ['rsh/Modules/Official/spill/spill', ['host']],
  ['rsh/Modules/Official/sandbox/sandbox', ['host']],
  ['rsh/Modules/Official/shell/shell', ['host']],
  ['rsh/Modules/Official/attachment/attachment', ['host']],
  ['rsh/Core/subprocess/subprocess', ['host']],
  ['rsh/Modules/Official/fs/fs', ['host', 'client']],
  ['rsh/Engine/llm/llm', ['host', 'client']],
  ['rsh/Engine/core/session', ['host', 'client']],
  ['rsh/Engine/session/session-persistence', ['host', 'client']],
  ['rsh/Programs/Web/client/modules', ['client']],
  ['rsh/Programs/Web/client/web', ['client']],
  ['rsh/Core/util/launch-environment', ['host', 'client']],
  ['rsh/Modules/Official/credentials/credentials', ['host', 'client']],
  ['rsh/Modules/Official/settings/settings', ['host']],
])

/** Compatibility peers whose imports are restricted to mixed packages' legacy entries. */
export const nativeCompatibilityOnlyPeers: ReadonlyMap<string, readonly string[]> = new Map([
  ['rsh/Modules/Official/todo/tool-todo', ['@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-session-projection', '@deepseek-ai/dsh-tools']],
  ['rsh/Modules/Official/fs/tool-fs-search', ['@deepseek-ai/dsh-tools', '@deepseek-ai/dsh-system-prompt']],
  ['rsh/Modules/Official/interaction/user-questions', ['@deepseek-ai/dsh-scope']],
  ['rsh/Modules/Official/interaction/tool-ask-user', ['@deepseek-ai/dsh-tools']],
  ['rsh/Modules/Official/fs/fs', ['@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-plugin-host']],
  ['rsh/Engine/core/session', ['@deepseek-ai/dsh-scope']],
  ['rsh/Engine/llm/llm', ['@deepseek-ai/dsh-typert-protocol']],
  ['rsh/Core/storage/storage-domain', ['@deepseek-ai/schemastery']],
  ['rsh/Core/storage/storage-json', ['@deepseek-ai/schemastery']],
  ['rsh/Modules/Official/fs/tool-fs', ['@deepseek-ai/dsh-tools', '@deepseek-ai/dsh-attachment']],
  ['rsh/Modules/Official/mcp/mcp-client', ['@deepseek-ai/dsh-scope', '@deepseek-ai/dsh-tools']],
  ['rsh/Engine/preset/agent-presets', [
    '@deepseek-ai/cordis-plugin-include', '@deepseek-ai/cordis-plugin-loader',
    '@deepseek-ai/dsh-atomic-write', '@deepseek-ai/dsh-home-paths',
    '@deepseek-ai/dsh-scope', '@deepseek-ai/dsh-typert-protocol',
  ]],
])

/** Additional Cordis-free exports shared by mixed packages' native entries. */
export const nativeSafeSourceSubpaths: ReadonlyMap<string, readonly string[]> = new Map([
  ['rsh/Programs/Web/client/native-session', ['./follow-types', './model-controls', './human']],
  ['rsh/Engine/core/native-model-execution', ['./model-selection', './model-directory', './adapter-directory']],
  ['rsh/Engine/llm/native-model-selection', ['./types']],
  ['rsh/Programs/CLI', ['./native-profile']],
  ['rsh/Programs/DesktopHost', ['./native-host']],
  ['rsh/Modules/Official/terminal/terminal', ['./protocol', './error']],
  ['rsh/Engine/llm/llm', ['./message']],
  ['rsh/Modules/Official/interaction/user-questions', ['./protocol', './broker']],
  ['rsh/Core/util/launch-environment', ['./layers']],
  ['rsh/Modules/Official/fs/tool-fs', ['./image-core']],
  ['rsh/Modules/Official/attachment/attachment-local', ['./backend', './request-store']],
  ['rsh/Engine/llm/deepseek-llm-api-extensions', ['./types']],
  ['rsh/Modules/Official/mcp/mcp-client', ['./types']],
  ['rsh/Engine/core/native-tools', ['./types', './presentation', './json-schema', './code-output', './sdk-typescript', './sdk-python', './ordered-dispatch']],
  ['rsh/Engine/core/native-session-execution', ['./root-route', './read-history']],
  ['rsh/Engine/core/native-agent', ['./inbox']],
  ['rsh/Programs/Web/client/connection', ['./native-host', './native-http-bridge']],
  ['rsh/Programs/Web/host/native-web-assets', ['./native-client']],
  ['rsh/Core/storage/storage', ['./backend']],
  ['rsh/Modules/Official/shell/pwsh-local', ['./resolve']],
  ['rsh/Modules/Official/shell/shell-env', ['./definition']],
  ['rsh/Modules/Official/attachment/attachment', ['./types', './brand', './error', './admission', './request-projection']],
  ['rsh/Modules/Official/fs/fs', ['./operations', './types']],
  ['rsh/Modules/Official/sandbox/sandbox', ['./native-types']],
  ['rsh/Engine/core/session', ['./types', './surface', './event-validation']],
  ['rsh/Engine/session/session-persistence', ['./deletion']],
  ['rsh/Engine/preset/agent-presets', ['./native-definition', './selection']],
  ['rsh/Modules/Official/workspace/workspace', ['./workspace-types']],
])

/** Additional native exports compiled only for the Host. */
export const nativeSafeSourceEntryTargets: ReadonlyMap<string, readonly ('host' | 'client')[]> = new Map([
  ['rsh/Engine/core/native-model-execution/model-selection', ['host', 'client']],
  ['rsh/Engine/core/native-model-execution/model-directory', ['host']],
  ['rsh/Engine/core/native-model-execution/adapter-directory', ['host']],
  ['rsh/Engine/llm/native-model-selection/types', ['host', 'client']],
  ['rsh/Programs/CLI/native-profile', ['host']],
  ['rsh/Programs/DesktopHost/native-host', ['host']],
  ['rsh/Modules/Official/terminal/terminal/protocol', ['host']],
  ['rsh/Modules/Official/terminal/terminal/error', ['host']],
  ['rsh/Modules/Official/interaction/user-questions/protocol', ['host', 'client']],
  ['rsh/Modules/Official/interaction/user-questions/broker', ['host']],
  ['rsh/Core/util/launch-environment/layers', ['host']],
  ['rsh/Modules/Official/fs/tool-fs/image-core', ['host']],
  ['rsh/Modules/Official/attachment/attachment-local/backend', ['host']],
  ['rsh/Modules/Official/attachment/attachment-local/request-store', ['host']],
  ['rsh/Modules/Official/attachment/attachment/admission', ['host']],
  ['rsh/Modules/Official/attachment/attachment/request-projection', ['host']],
  ['rsh/Modules/Official/attachment/attachment/brand', ['host', 'client']],
  ['rsh/Modules/Official/attachment/attachment/error', ['host', 'client']],
  ['rsh/Engine/llm/deepseek-llm-api-extensions/types', ['host']],
  ['rsh/Modules/Official/mcp/mcp-client/types', ['host']],
  ['rsh/Engine/core/native-tools/types', ['host', 'client']],
  ['rsh/Engine/session/session-persistence/deletion', ['host', 'client']],
  ['rsh/Engine/core/native-session-execution/root-route', ['host', 'client']],
  ['rsh/Engine/core/native-session-execution/read-history', ['host']],
  ['rsh/Engine/core/native-agent/inbox', ['host', 'client']],
  ['rsh/Engine/core/native-tools/presentation', ['host', 'client']],
  ['rsh/Engine/core/native-tools/json-schema', ['host']],
  ['rsh/Engine/core/native-tools/code-output', ['host']],
  ['rsh/Engine/core/native-tools/sdk-typescript', ['host']],
  ['rsh/Engine/core/native-tools/sdk-python', ['host']],
  ['rsh/Engine/core/native-tools/ordered-dispatch', ['host']],
  ['rsh/Programs/Web/client/connection/native-host', ['host']],
  ['rsh/Programs/Web/client/connection/native-http-bridge', ['host']],
  ['rsh/Programs/Web/host/native-web-assets/native-client', ['host']],
  ['rsh/Core/storage/storage/backend', ['host']],
  ['rsh/Modules/Official/shell/pwsh-local/resolve', ['host']],
  ['rsh/Modules/Official/shell/shell-env/definition', ['host']],
  ['rsh/Engine/preset/agent-presets/native-definition', ['host']],
])
