/** Explicit Cordis-free source owners in the native production graph. */

/** Package sources validated from their selected compiler faces by verify-native-dependencies. */
export const nativePackageDirectories: ReadonlySet<string> = new Set([
  'rsh/Programs/TUI/native-tui',
  'rsh/Programs/TUI/terminal-ui',
  'rsh/Core/identity/anonymous-user-id',
  'rsh/Modules/Official/shell/shell-process-local',
  'rsh/Modules/Official/shell/shell-sandbox-core',
  'rsh/Core/subprocess/win32-process',
  'rsh/Core/util/http-proxy',
  'rsh/Core/util/atomic-write',
  'rsh/Core/runtime-diagnostics/native-runtime',
  'rsh/Core/util/brand',
  'rsh/Core/util/crypto',
  'rsh/Core/util/errors',
  'rsh/Core/util/home-paths',
  'rsh/Core/util/http-routes',
  'rsh/Core/util/json-rpc-line',
  'rsh/Core/util/native-command',
  'rsh/Core/util/output-retention',
  'rsh/Core/util/timeout',
  'rsh/Core/util/values',
  'rsh/Core/settings/settings-definition',
  'rsh/Engine/session/session-format',
  'rsh/Engine/session/session-format-catalog',
  'rsh/Engine/session/session-format-v0-to-v1',
  'rsh/Engine/session/session-format-v1-to-v2',
  'rsh/Engine/session/session-format-v2-to-v3',
  'rsh/Engine/context/native-time-context',
  'rsh/Engine/workspace/workspace-definition',
  'rsh/Engine/core/native-agent',
  'rsh/Engine/core/native-session-execution',
  'rsh/Engine/core/approval-definition',
  'rsh/Engine/core/code-runtime-definition',
  'rsh/Modules/Official/code-runtime/native-code-runtime',
  'rsh/Modules/Official/code-runtime/tool-code-runtime',
  'rsh/Modules/Official/code-runtime/code-runtime-process-sandbox',
  'rsh/Engine/core/native-headless',
  'rsh/Engine/core/native-jobs',
  'rsh/Engine/core/native-model-execution',
  'rsh/Engine/llm/native-model-selection',
  'rsh/Engine/core/native-prompt',
  'rsh/Engine/core/native-tools',
  'rsh/Engine/preset/agent-preset-standing',
  'rsh/Engine/subagent/subagent-protocol',
  'rsh/Engine/subagent/sdk-protocol',
  'rsh/Engine/subagent/sdk-runtime',
  'rsh/Engine/subagent/native-subagent',
  'rsh/Engine/subagent/native-tool-subagent-list-agents',
  'rsh/Engine/jobs/native-tool-jobs',
  'rsh/Modules/Official/interaction/native-approval',
  'rsh/Modules/Official/interaction/user-question-broker',
  'rsh/Modules/Official/subagent/sdk-child',
  'rsh/Modules/Official/subagent/codex-app-server',
  'rsh/Modules/Official/sandbox/native-sandbox-policy',
  'rsh/Modules/Official/sandbox/sandbox-windows-acl',
  'rsh/Programs/Web/api/native-web-session-controller',
  'rsh/Programs/Web/client/native-session',
  'rsh/Programs/Web/client/native-application',
  'rsh/Programs/Web/host/native-web-host',
  'rsh/Programs/ACP/packages/native-acp',
  'rsh/Programs/SDK/packages/native-server',
  'rsh/Programs/SDK/packages/client',
  'rsh/Programs/Web/host/native-web-assets',
  'rsh/Programs/Web/client/store',
  'rsh/Programs/Web/client/ui-slots',
  'rsh/Programs/Web/client/ui-primitives',
  'rsh/Core/util/workspace-path',
  'rsh/Core/util/chunked-list',
  'rsh/Core/util/deque',
  'rsh/Core/util/package-manifest',
  'rsh/Core/util/time',
  'rsh/Programs/Web/client/ui-dockkit',
])

/** Native-profile Client packages that do not implement the Cordis module-table entry. */
export const nativeProfileClientDirectories: ReadonlySet<string> = new Set([
  'rsh/Programs/Web/client/native-session',
  'rsh/Programs/Web/client/native-application',
])

/** Explicit compiler faces for pure packages with a Host-only implementation. */
export const nativePackageTargets: ReadonlyMap<string, readonly ('host' | 'client')[]> = new Map([
  ['rsh/Core/util/http-routes', ['host', 'client']],
  ['rsh/Programs/Web/client/ui-primitives', ['client']],
  ['rsh/Programs/TUI/native-tui', ['host']],
  ['rsh/Programs/TUI/terminal-ui', ['host']],
  ['rsh/Engine/preset/agent-preset-standing', ['host']],
  ['rsh/Core/identity/anonymous-user-id', ['host']],
  ['rsh/Modules/Official/shell/shell-process-local', ['host']],
  ['rsh/Modules/Official/shell/shell-sandbox-core', ['host']],
  ['rsh/Engine/core/native-tools', ['host']],
  ['rsh/Engine/core/native-model-execution', ['host']],
  ['rsh/Engine/core/approval-definition', ['host']],
  ['rsh/Engine/core/code-runtime-definition', ['host']],
  ['rsh/Engine/llm/native-model-selection', ['host']],
  ['rsh/Modules/Official/interaction/user-question-broker', ['host']],
  ['rsh/Modules/Official/subagent/sdk-child', ['host']],
  ['rsh/Modules/Official/subagent/codex-app-server', ['host']],
  ['rsh/Engine/core/native-session-execution', ['host']],
  ['rsh/Modules/Official/sandbox/sandbox-windows-acl', ['host']],
  ['rsh/Modules/Official/code-runtime/native-code-runtime', ['host']],
  ['rsh/Modules/Official/code-runtime/tool-code-runtime', ['host']],
  ['rsh/Modules/Official/code-runtime/code-runtime-process-sandbox', ['host']],
  ['rsh/Programs/Web/api/native-web-session-controller', ['host']],
  ['rsh/Programs/Web/client/native-session', ['client']],
  ['rsh/Programs/Web/client/native-application', ['client']],
  ['rsh/Programs/Web/host/native-web-host', ['host']],
  ['rsh/Programs/ACP/packages/native-acp', ['host']],
  ['rsh/Programs/SDK/packages/native-server', ['host']],
  ['rsh/Engine/subagent/sdk-protocol', ['host']],
  ['rsh/Engine/subagent/sdk-runtime', ['host']],
  ['rsh/Programs/SDK/packages/client', ['host']],
  ['rsh/Programs/Web/host/native-web-assets', ['host']],
])

/** Mixed legacy packages whose Cordis entry and native installer share a package. */
export const mixedNativeEntryDirectories: ReadonlyMap<string, string> = new Map([
  ['rsh/Modules/Official/webhook/webhook-github', 'Cordis and Native GitHub ingress share raw-body HMAC verification while selected listeners and root execution remain sole authorities'],
  ['rsh/Modules/Official/webhook/webhook', 'Cordis and Native trusted-rule registration share neutral request and delivery Definitions'],
  ['rsh/Modules/Official/interaction/permission-presets', 'Cordis and Native permission selection share preset facts while Native applies through the selected root Session owner'],
  ['rsh/Modules/Official/automation/task-scheduler', 'Native and Cordis schedulers share SQLite plan facts while selected Programs own Agent execution and Session writers'],
  ['rsh/Engine/llm/token-meter', 'Native and Cordis Providers share the durable replay estimator'],
  ['rsh/Engine/llm/llm-retry', 'Native and Cordis recovery policies share the durable retry schedule and events'],
  ['rsh/Modules/Official/guard/timeout-policy', 'Native and Cordis execution policies share the declared-budget TOOL_TIMEOUT outcome'],
  ['rsh/Modules/Official/guard/repeat-tool-reminder', 'Native and Cordis settlement policies share repeat detection and reminder text'],
  ['rsh/Engine/subagent/tool-subagent', 'Native and Cordis Consumers delegate through their selected Subagent Provider'],
  ['rsh/Engine/subagent/tool-subagent-control', 'Native and Cordis controls route adjacent messages and interruption through their selected Subagent Provider'],
  ['rsh/Engine/goal/goal', 'Native Goal service and Cordis service share event-sourced state and request facts'],
  ['rsh/Engine/goal/goal-round-driver', 'Native and Cordis round drivers share continuation rules and prompts'],
  ['rsh/Engine/goal/tool-goal', 'Native and Cordis Goal tools share schemas, validation and presentation'],
  ['rsh/Engine/goal/command-goal', 'Native and Cordis Goal commands share lifecycle request facts'],
  ['rsh/Modules/Official/interaction/commands', 'Native command service and Cordis registry share parsed and durable command facts'],
  ['rsh/Engine/compaction/compaction-basic', 'Native and Cordis Providers share range selection, summarization and the durable compaction bracket'],
  ['rsh/Engine/compaction/compaction-tool-result-pruner', 'Native and Cordis pruners share tool-result shadow pricing and replacement'],
  ['rsh/Engine/compaction/command-compact', 'Native and Cordis /compact commands share argument validation and result presentation'],
  ['rsh/Engine/workflow/workflow', 'Native and Cordis Definitions expose one workflow lifecycle vocabulary'],
  ['rsh/Engine/workflow/workflow-worker-thread', 'Native and Cordis Providers share the worker controller and WorkerRun lifecycle'],
  ['rsh/Engine/workflow/tool-workflow', 'Native and Cordis workflow Consumers share foreground lifecycle and progress recording'],
  ['rsh/Engine/workflow/tool-ralph', 'Native and Cordis Ralph Consumers share fixed scripts and terminal validation'],
  ['rsh/Modules/Official/todo/tool-todo', 'Native and Cordis todo consumers share list normalization and durable Session events'],
  ['rsh/Modules/Official/plan/plan-mode', 'Native and Cordis plan-mode Consumers share the durable mode event, review question and command copy'],
  ['rsh/Engine/session/session-title', 'Native and Cordis title services share the durable title event, provider contract and fallback normalization'],
  ['rsh/Engine/session/session-title-first-prompt-llm', 'Native and Cordis first-prompt title providers share the model-backed generation policy'],
  ['rsh/Engine/session/session-title-all-prompts-llm', 'Native and Cordis all-prompts title providers share the model-backed generation policy'],
  ['rsh/Modules/Official/fs/tool-fs-search', 'Cordis and native search Consumers share ripgrep execution, parsing and result retention'],
  ['rsh/Modules/Official/web/web', 'Cordis and native web services share provider selection and the provider-neutral request and result shapes'],
  ['rsh/Modules/Official/web/web-fetch-http', 'Cordis and native HTTP fetch providers share policy, limits and response decoding'],
  ['rsh/Modules/Official/web/web-search-deepseek', 'Cordis and native DeepSeek search providers share request construction, response parsing and request recording'],
  ['rsh/Modules/Official/web/web-search-exa', 'Cordis and native Exa search providers share request construction and response parsing'],
  ['rsh/Modules/Official/web/web-search-perplexity', 'Cordis and native Perplexity search providers share request construction and response parsing'],
  ['rsh/Modules/Official/web/tool-web', 'Cordis and native web tools share argument validation, result merging, render text and presentation meta'],
  ['rsh/Modules/Official/spill/spill-local', 'Cordis and native spill Providers share private writes and startup cleanup'],
  ['rsh/Engine/context/agent-instructions', 'Native and Cordis instruction Providers share discovery, rendering and durable reconciliation'],
  ['rsh/Modules/Official/interaction/user-questions', 'Native and Cordis human questions share protocol values and errors'],
  ['rsh/Modules/Official/interaction/tool-ask-user', 'Native and Cordis Consumers use the selected human question service'],
  ['rsh/Modules/Official/mcp/mcp-client', 'Cordis and native MCP Consumers share connection supervision and protocol tool projection'],
  ['rsh/Modules/Official/sandbox/sandbox-local', 'Cordis and native Providers share local confinement and grant ownership'],
  ['rsh/Modules/Official/shell/shell-env', 'Cordis and native installers share managed command environment facts'],
  ['rsh/Modules/Official/shell/bash-local', 'Cordis and native installers share managed process operations'],
  ['rsh/Modules/Official/shell/bash-sandbox', 'Cordis and native installers share confined process operations'],
  ['rsh/Modules/Official/shell/pwsh-local', 'Cordis and native installers share managed process operations'],
  ['rsh/Modules/Official/shell/pwsh-sandbox', 'Cordis and native installers share confined process operations'],
  ['rsh/Modules/Official/shell/tool-bash', 'Cordis and native Consumers share Bash tool presentation'],
  ['rsh/Modules/Official/shell/tool-pwsh', 'Cordis and native Consumers share PowerShell tool presentation'],
  ['rsh/Modules/Official/terminal/terminal', 'Cordis and native Definitions share Agent-owned PTY lifecycle'],
  ['rsh/Modules/Official/terminal/terminal-bash', 'Cordis and native Providers share the subprocess terminal primitive'],
  ['rsh/Modules/Official/terminal/tool-terminal', 'Cordis and native Consumers share terminal lifecycle tools'],
  ['rsh/Modules/Official/fs/tool-fs', 'Cordis and native value tools share filesystem validation, guards and presentation'],
  ['rsh/Modules/Official/attachment/attachment-local', 'Cordis and native attachment Providers share immutable objects and transform ownership'],
  ['rsh/Modules/Official/llm/llm-pi-ai', 'Cordis and native pi-ai Providers share real adapter, catalog and auth operations'],
  ['rsh/Modules/Official/llm/llm-deepseek', 'Cordis and native official Providers share real HTTP/SSE adapter and static configuration'],
  ['rsh/Core/subprocess/subprocess-local', 'Cordis and native Providers share managed process and terminal ownership'],
  ['rsh/Programs/Web/client/ui-renderer', 'Cordis and native Client entries share slot rendering'],
  ['rsh/Programs/Web/client/connection', 'Cordis and native Client entries share authenticated transport'],
  ['rsh/Programs/Web/client/locale', 'Native and compatibility Clients share dictionary values while each owns its locale installer'],
  ['rsh/Programs/Web/client/ui-theme', 'Native and compatibility Clients share theme values and styles while each owns preference and DOM projection'],
  ['rsh/Programs/Web/client/ui-session', 'Native Session presentation projects the existing controller while the compatibility entry adapts Host Session stores'],
  ['rsh/Programs/Web/client/ui-layout', 'Native and compatibility shells share AppFrame, layout store, panel actions, and theme presenter'],
  ['rsh/Programs/Web/client/ui-sidebar', 'Native and compatibility shells share SidebarRoot and slot contracts while each supplies Session navigation'],
  ['rsh/Programs/Web/client/ui-sidebar-right', 'Native and compatibility shells share the right panel package while Native presents selected Session facts'],
  ['rsh/Core/storage/storage', 'Cordis and native storage hubs share the backend registry'],
  ['rsh/Core/storage/storage-json', 'Cordis and native JSON Providers share atomic storage operations'],
  ['rsh/Core/storage/storage-domain', 'Cordis and native domain Providers share schemas and durability'],
  ['rsh/Engine/preset/agent-presets', 'Native standing composition leases and compatibility presets share durable selection facts'],
  ['rsh/Modules/Official/workspace/workspace', 'Native and Cordis Workspace Providers share the durable v2 registry'],
  ['rsh/Modules/Official/credentials/credentials-local', 'Cordis service and native credential installer share the file backend'],
  ['rsh/Modules/Official/settings/settings-file', 'Cordis and native settings Providers share the document format and atomic file owner'],
  ['rsh/Engine/session/session-persistence-jsonl', 'Cordis service and native storage entry share a package'],
  ['rsh/Modules/Official/fs/fs-local', 'Cordis filesystem Provider and native backend share a package'],
  ['rsh/Modules/Official/fs/fs-observation-policy', 'Cordis event policy and native entry share a package'],
  ['rsh/Modules/Official/fs/fs-sandbox', 'Cordis and native filesystem Providers share per-call sandbox enforcement'],
  ['rsh/Engine/session/session-title-first-prompt-llm', 'Native title generation delegates through the selected title and model capabilities while its legacy adapter remains optional'],
])

/** Mixed library exports that have native values or types but no installer manifest. */
export const mixedNativeLibraryDirectories: ReadonlyMap<string, readonly ('host' | 'client')[]> = new Map([
  ['rsh/Modules/Official/spill/spill', ['host']],
  ['rsh/Modules/Official/sandbox/sandbox', ['host']],
  ['rsh/Programs/Web/client/ui-slots', ['client']],
  ['rsh/Modules/Official/shell/shell', ['host']],
  ['rsh/Modules/Official/attachment/attachment', ['host']],
  ['rsh/Core/subprocess/subprocess', ['host']],
  ['rsh/Modules/Official/fs/fs', ['host', 'client']],
  ['rsh/Engine/llm/llm', ['host', 'client']],
  ['rsh/Engine/core/session', ['host', 'client']],
  ['rsh/Engine/compaction/compaction', ['host']],
  ['rsh/Engine/session/session-persistence', ['host', 'client']],
  ['rsh/Engine/session/session-title', ['host']],
  ['rsh/Programs/Web/client/modules', ['client']],
  ['rsh/Programs/Web/client/web', ['client']],
  ['rsh/Core/util/launch-environment', ['host', 'client']],
  ['rsh/Modules/Official/credentials/credentials', ['host', 'client']],
  ['rsh/Modules/Official/settings/settings', ['host']],
  ['rsh/Engine/session/session-title-llm', ['host']],
])

/** Compatibility peers whose imports are restricted to mixed packages' legacy entries. */
export const nativeCompatibilityOnlyPeers: ReadonlyMap<string, readonly string[]> = new Map([
  ['rsh/Modules/Official/webhook/webhook-github', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-http-routes-cordis']],
  ['rsh/Modules/Official/webhook/webhook', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-agent-default-model', '@deepseek-ai/dsh-agent-presets', '@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-llm', '@deepseek-ai/dsh-permission-presets', '@deepseek-ai/dsh-session', '@deepseek-ai/dsh-session-title', '@deepseek-ai/dsh-workspace']],
  ['rsh/Modules/Official/interaction/permission-presets', [
    '@deepseek-ai/cordis', '@deepseek-ai/dsh-compat-settings-definition', '@deepseek-ai/dsh-shell',
    '@deepseek-ai/dsh-commands', '@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-sandbox',
    '@deepseek-ai/dsh-sandbox-policy', '@deepseek-ai/dsh-session', '@deepseek-ai/dsh-session-projection',
    '@deepseek-ai/dsh-user-approval', '@deepseek-ai/dsh-settings',
  ]],
  ['rsh/Engine/subagent/tool-subagent', ['@deepseek-ai/dsh-scope', '@deepseek-ai/dsh-session', '@deepseek-ai/dsh-subagent', '@deepseek-ai/dsh-tools']],
  ['rsh/Engine/llm/token-meter', ['@deepseek-ai/dsh-compaction', '@deepseek-ai/dsh-llm-retry', '@deepseek-ai/dsh-session-projection']],
  ['rsh/Modules/Official/spill/spill-policy', ['@deepseek-ai/dsh-llm', '@deepseek-ai/dsh-session', '@deepseek-ai/dsh-tools']],
  ['rsh/Engine/subagent/tool-subagent-control', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-subagent', '@deepseek-ai/dsh-tools']],
  ['rsh/Engine/goal/goal', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-llm', '@deepseek-ai/dsh-scope', '@deepseek-ai/dsh-session-projection', '@deepseek-ai/dsh-typert-protocol']],
  ['rsh/Engine/goal/goal-round-driver', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-invariants']],
  ['rsh/Engine/goal/tool-goal', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-system-prompt', '@deepseek-ai/dsh-tools', '@deepseek-ai/dsh-session-projection']],
  ['rsh/Engine/goal/command-goal', ['@deepseek-ai/cordis']],
  ['rsh/Engine/compaction/compaction', ['@deepseek-ai/cordis']],
  ['rsh/Engine/compaction/compaction-basic', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent']],
  ['rsh/Engine/compaction/compaction-tool-result-pruner', ['@deepseek-ai/cordis']],
  ['rsh/Engine/compaction/command-compact', ['@deepseek-ai/cordis']],
  ['rsh/Modules/Official/interaction/commands', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-attachment', '@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-scope', '@deepseek-ai/dsh-typert-protocol']],
  ['rsh/Engine/workflow/workflow', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-session']],
  ['rsh/Engine/workflow/workflow-worker-thread', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-llm', '@deepseek-ai/dsh-session', '@deepseek-ai/dsh-subagent', '@deepseek-ai/dsh-tools']],
  ['rsh/Engine/workflow/tool-workflow', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-llm', '@deepseek-ai/dsh-session', '@deepseek-ai/dsh-system-prompt', '@deepseek-ai/dsh-tools']],
  ['rsh/Engine/workflow/tool-ralph', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-llm', '@deepseek-ai/dsh-subagent', '@deepseek-ai/dsh-system-prompt', '@deepseek-ai/dsh-tools']],
  ['rsh/Modules/Official/todo/tool-todo', ['@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-session-projection', '@deepseek-ai/dsh-tools']],
  ['rsh/Modules/Official/plan/plan-mode', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-session-projection', '@deepseek-ai/dsh-system-prompt', '@deepseek-ai/dsh-tools']],
  ['rsh/Engine/session/session-title', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-llm', '@deepseek-ai/dsh-session-projection']],
  ['rsh/Engine/session/session-title-first-prompt-llm', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-llm', '@deepseek-ai/dsh-session', '@deepseek-ai/dsh-session-title']],
  ['rsh/Engine/session/session-title-all-prompts-llm', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-llm', '@deepseek-ai/dsh-session', '@deepseek-ai/dsh-session-title']],
  ['rsh/Modules/Official/automation/task-scheduler', ['@deepseek-ai/dsh-tools', '@deepseek-ai/dsh-typert-protocol']],
  ['rsh/Modules/Official/fs/tool-fs-search', ['@deepseek-ai/dsh-tools', '@deepseek-ai/dsh-system-prompt']],
  ['rsh/Modules/Official/web/web', ['@deepseek-ai/cordis']],
  ['rsh/Modules/Official/web/web-fetch-http', ['@deepseek-ai/cordis']],
  ['rsh/Modules/Official/web/web-search-deepseek', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-agent', '@deepseek-ai/dsh-compat-settings-definition', '@deepseek-ai/dsh-session']],
  ['rsh/Modules/Official/web/web-search-exa', ['@deepseek-ai/cordis']],
  ['rsh/Modules/Official/web/web-search-perplexity', ['@deepseek-ai/cordis']],
  ['rsh/Modules/Official/web/tool-web', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-system-prompt', '@deepseek-ai/dsh-tools']],
  ['rsh/Modules/Official/terminal/tool-terminal', ['@deepseek-ai/dsh-tools']],
  ['rsh/Modules/Official/interaction/user-questions', ['@deepseek-ai/dsh-scope']],
  ['rsh/Modules/Official/interaction/tool-ask-user', ['@deepseek-ai/dsh-tools']],
  ['rsh/Modules/Official/shell/tool-pwsh', ['@deepseek-ai/dsh-tools']],
  ['rsh/Modules/Official/fs/fs', ['@deepseek-ai/dsh-invariants', '@deepseek-ai/dsh-plugin-host']],
  ['rsh/Modules/Official/fs/fs-local', ['@deepseek-ai/dsh-plugin-host']],
  ['rsh/Modules/Official/fs/fs-observation-policy', ['@deepseek-ai/dsh-plugin-host']],
  ['rsh/Modules/Official/fs/fs-sandbox', ['@deepseek-ai/cordis', '@deepseek-ai/dsh-plugin-host', '@deepseek-ai/dsh-sandbox-policy']],
  ['rsh/Engine/core/session', ['@deepseek-ai/dsh-scope']],
  ['rsh/Engine/llm/llm', ['@deepseek-ai/dsh-typert-protocol']],
  ['rsh/Core/storage/storage-domain', ['@deepseek-ai/schemastery']],
  ['rsh/Core/storage/storage-json', ['@deepseek-ai/schemastery']],
  ['rsh/Modules/Official/fs/tool-fs', ['@deepseek-ai/dsh-tools', '@deepseek-ai/dsh-attachment']],
  ['rsh/Modules/Official/mcp/mcp-client', ['@deepseek-ai/dsh-scope', '@deepseek-ai/dsh-tools']],
  ['rsh/Engine/preset/agent-presets', [
    '@deepseek-ai/cordis-plugin-include', '@deepseek-ai/cordis-plugin-loader',
    '@deepseek-ai/dsh-atomic-write', '@deepseek-ai/dsh-home-paths',
    '@deepseek-ai/dsh-scope', '@deepseek-ai/dsh-typert-protocol',
  ]],
])

/** Additional Cordis-free exports shared by mixed packages' native entries. */
export const nativeSafeSourceSubpaths: ReadonlyMap<string, readonly string[]> = new Map([
  ['rsh/Modules/Official/webhook/webhook', ['./definition', './types']],
  ['rsh/Modules/Official/interaction/permission-presets', ['./native-definition']],
  ['rsh/Engine/session/session-projection', ['./types']],
  ['rsh/Engine/session/session-title', ['./normalize', './types']],
  ['rsh/Engine/goal/goal', ['./types']],
  ['rsh/Modules/Official/interaction/commands', ['./facts', './brand']],
  ['rsh/Programs/Web/client/ui-conversation', ['./tool-records', './conversation-copy']],
  ['rsh/Programs/Web/client/ui-tool', ['./tool-renderer']],
  ['rsh/Programs/Web/client/locale', ['./dictionary']],
  ['rsh/Modules/Official/spill/spill-policy', ['./notice']],
  ['rsh/Modules/Official/todo/tool-todo', ['./client-native']],
  ['rsh/Engine/subagent/subagent-protocol', ['./descriptor', './assistant-output']],
  ['rsh/Programs/Web/client/native-session', ['./follow-types', './model-controls', './human', './list-types']],
  ['rsh/Engine/core/native-model-execution', ['./model-selection', './model-directory', './adapter-directory']],
  ['rsh/Engine/llm/native-model-selection', ['./types']],
  ['rsh/Programs/CLI', ['./native-profile']],
  ['rsh/Programs/DesktopHost', ['./native-host']],
  ['rsh/Modules/Official/terminal/terminal', ['./protocol', './error']],
  ['rsh/Engine/llm/llm', ['./message']],
  ['rsh/Modules/Official/interaction/user-questions', ['./protocol', './broker']],
  ['rsh/Core/util/launch-environment', ['./layers']],
  ['rsh/Core/subprocess/subprocess-local', ['./child-connection']],
  ['rsh/Modules/Official/fs/tool-fs', ['./image-core']],
  ['rsh/Modules/Official/attachment/attachment-local', ['./backend', './request-store']],
  ['rsh/Modules/Official/llm/deepseek-llm-api-extensions', ['./types']],
  ['rsh/Modules/Official/mcp/mcp-client', ['./types', './acp-config']],
  ['rsh/Engine/core/native-tools', ['./types', './presentation', './json-schema', './code-output', './sdk-typescript', './sdk-python', './ordered-dispatch']],
  ['rsh/Engine/workflow/tool-workflow', ['./foreground']],
  ['rsh/Engine/workflow/tool-ralph', ['./runtime']],
  ['rsh/Engine/workflow/workflow', ['./errors', './types']],
  ['rsh/Engine/core/native-session-execution', ['./root-route', './read-history']],
  ['rsh/Engine/core/native-agent', ['./inbox', './consumed-work']],
  ['rsh/Programs/Web/client/connection', ['./native-host', './native-http-bridge']],
  ['rsh/Programs/Web/host/native-web-assets', ['./native-client']],
  ['rsh/Core/storage/storage', ['./backend']],
  ['rsh/Modules/Official/shell/pwsh-local', ['./resolve']],
  ['rsh/Modules/Official/shell/shell-env', ['./definition']],
  ['rsh/Modules/Official/attachment/attachment', ['./types', './brand', './error', './admission', './request-projection']],
  ['rsh/Modules/Official/fs/fs', ['./operations', './types']],
  ['rsh/Modules/Official/fs/fs-local', ['./backend']],
  ['rsh/Modules/Official/sandbox/sandbox', ['./native-types', './roots']],
  ['rsh/Engine/core/session', ['./types', './surface', './event-validation']],
  ['rsh/Engine/session/session-projection', ['./types']],
  ['rsh/Engine/session/session-title', ['./types', './normalize']],
  ['rsh/Engine/session/session-title-llm', ['./native']],
  ['rsh/Programs/Web/client/ui-theme', ['./theme-contract']],
  ['rsh/Engine/session/session-persistence', ['./deletion']],
  ['rsh/Engine/preset/agent-presets', ['./native-definition', './selection']],
  ['rsh/Modules/Official/workspace/workspace', ['./workspace-types']],
  ['rsh/Modules/Official/subagent/codex-app-server', ['./wire']],
])

/** Additional native exports compiled only for the Host. */
export const nativeSafeSourceEntryTargets: ReadonlyMap<string, readonly ('host' | 'client')[]> = new Map([
  ['rsh/Modules/Official/interaction/permission-presets/native-definition', ['host']],
  ['rsh/Engine/session/session-title/normalize', ['host']],
  ['rsh/Core/subprocess/subprocess-local/child-connection', ['host']],
  ['rsh/Modules/Official/webhook/webhook/definition', ['host']],
  ['rsh/Modules/Official/webhook/webhook/types', ['host']],
  ['rsh/Programs/Web/client/ui-conversation/tool-records', ['client']],
  ['rsh/Programs/Web/client/ui-conversation/conversation-copy', ['client']],
  ['rsh/Programs/Web/client/ui-tool/tool-renderer', ['client']],
  ['rsh/Programs/Web/client/locale/dictionary', ['client']],
  ['rsh/Modules/Official/spill/spill-policy/notice', ['client']],
  ['rsh/Modules/Official/todo/tool-todo/client-native', ['host', 'client']],
  ['rsh/Engine/core/native-model-execution/model-selection', ['host', 'client']],
  ['rsh/Engine/core/native-model-execution/model-directory', ['host']],
  ['rsh/Engine/core/native-model-execution/adapter-directory', ['host']],
  ['rsh/Engine/llm/native-model-selection/types', ['host', 'client']],
  ['rsh/Programs/CLI/native-profile', ['host']],
  ['rsh/Programs/DesktopHost/native-host', ['host']],
  ['rsh/Modules/Official/sandbox/sandbox/roots', ['host']],
  ['rsh/Modules/Official/fs/fs-local/backend', ['host']],
  ['rsh/Modules/Official/terminal/terminal/protocol', ['host']],
  ['rsh/Modules/Official/terminal/terminal/error', ['host']],
  ['rsh/Modules/Official/interaction/user-questions/protocol', ['host', 'client']],
  ['rsh/Modules/Official/interaction/user-questions/broker', ['host']],
  ['rsh/Core/util/launch-environment/layers', ['host']],
  ['rsh/Modules/Official/fs/tool-fs/image-core', ['host']],
  ['rsh/Modules/Official/attachment/attachment-local/backend', ['host']],
  ['rsh/Modules/Official/attachment/attachment-local/request-store', ['host']],
  ['rsh/Modules/Official/attachment/attachment/admission', ['host']],
  ['rsh/Modules/Official/attachment/attachment/request-projection', ['host']],
  ['rsh/Modules/Official/attachment/attachment/brand', ['host', 'client']],
  ['rsh/Modules/Official/attachment/attachment/error', ['host', 'client']],
  ['rsh/Modules/Official/llm/deepseek-llm-api-extensions/types', ['host']],
  ['rsh/Modules/Official/mcp/mcp-client/types', ['host']],
  ['rsh/Modules/Official/mcp/mcp-client/acp-config', ['host']],
  ['rsh/Engine/core/native-tools/types', ['host', 'client']],
  ['rsh/Engine/session/session-persistence/deletion', ['host', 'client']],
  ['rsh/Engine/core/native-session-execution/root-route', ['host', 'client']],
  ['rsh/Engine/core/native-session-execution/read-history', ['host']],
  ['rsh/Engine/core/native-agent/inbox', ['host', 'client']],
  ['rsh/Engine/core/native-agent/consumed-work', ['host']],
  ['rsh/Engine/core/native-tools/presentation', ['host', 'client']],
  ['rsh/Engine/core/native-tools/json-schema', ['host']],
  ['rsh/Engine/core/native-tools/code-output', ['host']],
  ['rsh/Engine/core/native-tools/sdk-typescript', ['host']],
  ['rsh/Engine/core/native-tools/sdk-python', ['host']],
  ['rsh/Engine/core/native-tools/ordered-dispatch', ['host']],
  ['rsh/Engine/workflow/tool-workflow/foreground', ['host']],
  ['rsh/Engine/workflow/tool-ralph/runtime', ['host']],
  ['rsh/Engine/workflow/workflow/errors', ['host']],
  ['rsh/Programs/Web/client/connection/native-host', ['host']],
  ['rsh/Programs/Web/client/connection/native-http-bridge', ['host']],
  ['rsh/Programs/Web/host/native-web-assets/native-client', ['host']],
  ['rsh/Core/storage/storage/backend', ['host']],
  ['rsh/Modules/Official/shell/pwsh-local/resolve', ['host']],
  ['rsh/Modules/Official/shell/shell-env/definition', ['host']],
  ['rsh/Modules/Official/subagent/codex-app-server/wire', ['host']],
  ['rsh/Engine/preset/agent-presets/native-definition', ['host']],
  ['rsh/Engine/session/session-projection/types', ['host', 'client']],
  ['rsh/Engine/session/session-title-llm/native', ['host']],
  ['rsh/Programs/Web/client/native-session/list-types', ['host', 'client']],
  ['rsh/Programs/Web/client/ui-theme/theme-contract', ['client']],
])
